import { elementModel } from './canvas/canvas.component';

export const tableElements: elementModel[] = [
  {
    period: 1,
    positionGroup: 1,
    inactive: false,
    symbol: 'H',
    name: 'Hydrogen',
    mass: 1.008,
    Z: 1,
    valences: [1],
    group: 'Other nonmetals',
    x: 1,
    y: 1
  },
  {
    period: 1,
    positionGroup: 18,
    inactive: false,
    symbol: 'He',
    name: 'Helium',
    mass: 4.0026,
    Z: 2,
    valences: 'doublet stable',
    group: 'Noble gases',
    x: 18,
    y: 1
  },
  {
    period: 2,
    positionGroup: 1,
    inactive: false,
    symbol: 'Li',
    name: 'Lithium',
    mass: 6.94,
    Z: 3,
    valences: [1],
    group: 'Alkali metals',
    x: 1,
    y: 2
  },
  {
    period: 2,
    positionGroup: 2,
    inactive: false,
    symbol: 'Be',
    name: 'Beryllium',
    mass: 9.0122,
    Z: 4,
    valences: [2],
    group: 'Alkaline earth metals',
    x: 2,
    y: 2
  },
  {
    period: 2,
    positionGroup: 13,
    inactive: false,
    symbol: 'B',
    name: 'Boron',
    mass: 10.81,
    Z: 5,
    valences: [3],
    group: 'Metalloids',
    x: 13,
    y: 2,
    anionValence: 3
  },
  {
    period: 2,
    positionGroup: 14,
    inactive: false,
    symbol: 'C',
    name: 'Carbon',
    mass: 12.011,
    Z: 6,
    valences: [2, 4],
    group: 'Other nonmetals',
    x: 14,
    y: 2,
    anionValence: 2
  },
  {
    period: 2,
    positionGroup: 15,
    inactive: false,
    symbol: 'N',
    name: 'Nitrogen',
    mass: 14.007,
    Z: 7,
    valences: [-3, -2, -1, 2, 3, 4, 5],
    group: 'Other nonmetals',
    x: 15,
    y: 2,
    anionValence: 1
  },
  {
    period: 2,
    positionGroup: 16,
    inactive: false,
    symbol: 'O',
    name: 'Oxygen',
    mass: 15.999,
    Z: 8,
    valences: [-2],
    group: 'Other nonmetals',
    x: 16,
    y: 2
  },
  {
    period: 2,
    positionGroup: 17,
    inactive: false,
    symbol: 'F',
    name: 'Fluorine',
    mass: 18.998,
    Z: 9,
    valences: [-1],
    group: 'Other nonmetals',
    x: 17,
    y: 2
  },
  {
    period: 2,
    positionGroup: 18,
    inactive: false,
    symbol: 'Ne',
    name: 'Neon',
    mass: 20.18,
    Z: 10,
    valences: 'doublet stable',
    group: 'Noble gases',
    x: 18,
    y: 2
  },
  {
    period: 3,
    positionGroup: 1,
    inactive: false,
    symbol: 'Na',
    name: 'Sodium',
    mass: 22.99,
    Z: 11,
    valences: [1],
    group: 'Alkali metals',
    x: 1,
    y: 3
  },
  {
    period: 3,
    positionGroup: 2,
    inactive: false,
    symbol: 'Mg',
    name: 'Magnesium',
    mass: 24.31,
    Z: 12,
    valences: [2],
    group: 'Alkaline earth metals',
    x: 2,
    y: 3
  },
  {
    period: 3,
    positionGroup: 13,
    inactive: false,
    symbol: 'Al',
    name: 'Aluminum',
    mass: 26.98,
    Z: 13,
    valences: [3],
    group: 'Post-transition metals',
    x: 13,
    y: 3
  },
  {
    period: 3,
    positionGroup: 14,
    inactive: false,
    symbol: 'Si',
    name: 'Silicon',
    mass: 28.09,
    Z: 14,
    valences: [-4, 4],
    group: 'Metalloids',
    x: 14,
    y: 3
  },
  {
    period: 3,
    positionGroup: 15,
    inactive: false,
    symbol: 'P',
    name: 'Phosphorus',
    mass: 30.97,
    Z: 15,
    valences: [-3, 1, 3, 5],
    group: 'Other nonmetals',
    x: 15,
    y: 3,
    anionValence: 3
  },
  {
    period: 3,
    positionGroup: 16,
    inactive: false,
    symbol: 'S',
    name: 'Sulfur',
    mass: 32.07,
    Z: 16,
    valences: [-2, 2, 4, 6],
    group: 'Other nonmetals',
    x: 16,
    y: 3,
    anionValence: 2
  },
  {
    period: 3,
    positionGroup: 17,
    inactive: false,
    symbol: 'Cl',
    name: 'Chlorine',
    mass: 35.45,
    Z: 17,
    valences: [-1, 1, 3, 5, 7],
    group: 'Other nonmetals',
    x: 17,
    y: 3,
    anionValence: 1
  },
  {
    period: 3,
    positionGroup: 18,
    inactive: false,
    symbol: 'Ar',
    name: 'Argon',
    mass: 39.95,
    Z: 18,
    valences: 'doublet stable',
    group: 'Noble gases',
    x: 18,
    y: 3
  },
  {
    period: 4,
    positionGroup: 1,
    inactive: false,
    symbol: 'K',
    name: 'Potassium',
    mass: 39.1,
    Z: 19,
    valences: [1],
    group: 'Alkali metals',
    x: 1,
    y: 4
  },
  {
    period: 4,
    positionGroup: 2,
    inactive: false,
    symbol: 'Ca',
    name: 'Calcium',
    mass: 40.08,
    Z: 20,
    valences: [2],
    group: 'Alkaline earth metals',
    x: 2,
    y: 4
  },
  {
    period: 4,
    positionGroup: 3,
    inactive: false,
    symbol: 'Sc',
    name: 'Scandium',
    mass: 44.96,
    Z: 21,
    valences: [3],
    group: 'Transition metals',
    x: 3,
    y: 4
  },
  {
    period: 4,
    positionGroup: 4,
    inactive: false,
    symbol: 'Ti',
    name: 'Titanium',
    mass: 47.87,
    Z: 22,
    valences: [2, 3, 4],
    group: 'Transition metals',
    x: 4,
    y: 4
  },
  {
    period: 4,
    positionGroup: 5,
    inactive: false,
    symbol: 'V',
    name: 'Vanadium',
    mass: 50.94,
    Z: 23,
    valences: [2, 3, 4, 5],
    group: 'Transition metals',
    x: 5,
    y: 4
  },
  {
    period: 4,
    positionGroup: 6,
    inactive: false,
    symbol: 'Cr',
    name: 'Chromium',
    mass: 51.99,
    Z: 24,
    valences: [2, 3, 4, 5, 6],
    group: 'Transition metals',
    x: 6,
    y: 4
  },
  {
    period: 4,
    positionGroup: 7,
    inactive: false,
    symbol: 'Mn',
    name: 'Manganese',
    mass: 54.94,
    Z: 25,
    valences: [2, 3, 4, 5, 6, 7],
    group: 'Transition metals',
    x: 7,
    y: 4
  },
  {
    period: 4,
    positionGroup: 8,
    inactive: false,
    symbol: 'Fe',
    name: 'Iron',
    mass: 55.85,
    Z: 26,
    valences: [2, 3, 4, 6],
    group: 'Transition metals',
    x: 8,
    y: 4
  },
  {
    period: 4,
    positionGroup: 9,
    inactive: false,
    symbol: 'Co',
    name: 'Cobalt',
    mass: 58.93,
    Z: 27,
    valences: [2, 3, 4],
    group: 'Transition metals',
    x: 9,
    y: 4
  },
  {
    period: 4,
    positionGroup: 10,
    inactive: false,
    symbol: 'Ni',
    name: 'Nickel',
    mass: 58.69,
    Z: 28,
    valences: [2, 3, 4],
    group: 'Transition metals',
    x: 10,
    y: 4
  },
  {
    period: 4,
    positionGroup: 11,
    inactive: false,
    symbol: 'Cu',
    name: 'Copper',
    mass: 63.55,
    Z: 29,
    valences: [1, 2],
    group: 'Transition metals',
    x: 11,
    y: 4
  },
  {
    period: 4,
    positionGroup: 12,
    inactive: false,
    symbol: 'Zn',
    name: 'Zinc',
    mass: 65.38,
    Z: 30,
    valences: [2],
    group: 'Transition metals',
    x: 12,
    y: 4
  },
  {
    period: 4,
    positionGroup: 13,
    inactive: false,
    symbol: 'Ga',
    name: 'Gallium',
    mass: 69.72,
    Z: 31,
    valences: [3],
    group: 'Post-transition metals',
    x: 13,
    y: 4
  },
  {
    period: 4,
    positionGroup: 14,
    inactive: false,
    symbol: 'Ge',
    name: 'Germanium',
    mass: 72.63,
    Z: 32,
    valences: [-4, 2, 4],
    group: 'Metalloids',
    x: 14,
    y: 4
  },
  {
    period: 4,
    positionGroup: 15,
    inactive: false,
    symbol: 'As',
    name: 'Arsenic',
    mass: 74.92,
    Z: 33,
    valences: [-3, 2, 3, 5],
    group: 'Metalloids',
    x: 15,
    y: 4
  },
  {
    period: 4,
    positionGroup: 16,
    inactive: false,
    symbol: 'Se',
    name: 'Selenium',
    mass: 78.97,
    Z: 34,
    valences: [-2, 4, 6],
    group: 'Other nonmetals',
    x: 16,
    y: 4
  },
  {
    period: 4,
    positionGroup: 17,
    inactive: false,
    symbol: 'Br',
    name: 'Bromine',
    mass: 79.9,
    Z: 35,
    valences: [-1, 1, 3, 5, 7],
    group: 'Other nonmetals',
    x: 17,
    y: 4,
    anionValence: 1
  },
  {
    period: 4,
    positionGroup: 18,
    inactive: false,
    symbol: 'Kr',
    name: 'Krypton',
    mass: 83.8,
    Z: 36,
    valences: 'doublet stable',
    group: 'Noble gases',
    x: 18,
    y: 4
  },
  {
    period: 5,
    positionGroup: 1,
    inactive: false,
    symbol: 'Rb',
    name: 'Rubidium',
    mass: 85.47,
    Z: 37,
    valences: [1],
    group: 'Alkali metals',
    x: 1,
    y: 5
  },
  {
    period: 5,
    positionGroup: 2,
    inactive: false,
    symbol: 'Sr',
    name: 'Strontium',
    mass: 87.62,
    Z: 38,
    valences: [2],
    group: 'Alkaline earth metals',
    x: 2,
    y: 5
  },
  {
    period: 5,
    positionGroup: 3,
    inactive: false,
    symbol: 'Y',
    name: 'Yttrium',
    mass: 88.91,
    Z: 39,
    valences: [3],
    group: 'Transition metals',
    x: 3,
    y: 5
  },
  {
    period: 5,
    positionGroup: 4,
    inactive: false,
    symbol: 'Zr',
    name: 'Zirconium',
    mass: 91.22,
    Z: 40,
    valences: [4],
    group: 'Transition metals',
    x: 4,
    y: 5
  },
  {
    period: 5,
    positionGroup: 5,
    inactive: false,
    symbol: 'Nb',
    name: 'Niobium',
    mass: 92.91,
    Z: 41,
    valences: [3, 5],
    group: 'Transition metals',
    x: 5,
    y: 5
  },
  {
    period: 5,
    positionGroup: 6,
    inactive: false,
    symbol: 'Mo',
    name: 'Molybdenum',
    mass: 95.94,
    Z: 42,
    valences: [2, 3, 4, 5, 6],
    group: 'Transition metals',
    x: 6,
    y: 5
  },
  {
    period: 5,
    positionGroup: 7,
    inactive: false,
    symbol: 'Tc',
    name: 'Technetium',
    mass: 98,
    Z: 43,
    valences: [4, 7],
    group: 'Transition metals',
    x: 7,
    y: 5
  },
  {
    period: 5,
    positionGroup: 8,
    inactive: false,
    symbol: 'Ru',
    name: 'Ruthenium',
    mass: 101.1,
    Z: 44,
    valences: [2, 3, 4, 6, 8],
    group: 'Transition metals',
    x: 8,
    y: 5
  },
  {
    period: 5,
    positionGroup: 9,
    inactive: false,
    symbol: 'Rh',
    name: 'Rhodium',
    mass: 102.9,
    Z: 45,
    valences: [1, 2, 3, 4],
    group: 'Transition metals',
    x: 9,
    y: 5
  },
  {
    period: 5,
    positionGroup: 10,
    inactive: false,
    symbol: 'Pd',
    name: 'Palladium',
    mass: 106.4,
    Z: 46,
    valences: [2, 4],
    group: 'Transition metals',
    x: 10,
    y: 5
  },
  {
    period: 5,
    positionGroup: 11,
    inactive: false,
    symbol: 'Ag',
    name: 'Silver',
    mass: 107.9,
    Z: 47,
    valences: [1, 2, 3],
    group: 'Transition metals',
    x: 11,
    y: 5
  },
  {
    period: 5,
    positionGroup: 12,
    inactive: false,
    symbol: 'Cd',
    name: 'Cadmium',
    mass: 112.4,
    Z: 48,
    valences: [2],
    group: 'Transition metals',
    x: 12,
    y: 5
  },
  {
    period: 5,
    positionGroup: 13,
    inactive: false,
    symbol: 'In',
    name: 'Indium',
    mass: 114.8,
    Z: 49,
    valences: [1, 2, 3],
    group: 'Post-transition metals',
    x: 13,
    y: 5
  },
  {
    period: 5,
    positionGroup: 14,
    inactive: false,
    symbol: 'Sn',
    name: 'Tin',
    mass: 118.7,
    Z: 50,
    valences: [2, 4],
    group: 'Post-transition metals',
    x: 14,
    y: 5
  },
  {
    period: 5,
    positionGroup: 15,
    inactive: false,
    symbol: 'Sb',
    name: 'Antimony',
    mass: 121.8,
    Z: 51,
    valences: [-3, 3, 5],
    group: 'Metalloids',
    x: 15,
    y: 5
  },
  {
    period: 5,
    positionGroup: 16,
    inactive: false,
    symbol: 'Te',
    name: 'Tellurium',
    mass: 127.6,
    Z: 52,
    valences: [-2, 2, 4, 6],
    group: 'Metalloids',
    x: 16,
    y: 5
  },
  {
    period: 5,
    positionGroup: 17,
    inactive: false,
    symbol: 'I',
    name: 'Iodine',
    mass: 126.9,
    Z: 53,
    valences: [-1, 1, 3, 5, 7],
    group: 'Other nonmetals',
    x: 17,
    y: 5,
    anionValence: 1
  },
  {
    period: 5,
    positionGroup: 18,
    inactive: false,
    symbol: 'Xe',
    name: 'Xenon',
    mass: 131.3,
    Z: 54,
    valences: 'doublet stable',
    group: 'Noble gases',
    x: 18,
    y: 5
  },
  {
    period: 6,
    positionGroup: 1,
    inactive: false,
    symbol: 'Cs',
    name: 'Cesium',
    mass: 132.9,
    Z: 55,
    valences: [1],
    group: 'Alkali metals',
    x: 1,
    y: 6
  },
  {
    period: 6,
    positionGroup: 2,
    inactive: false,
    symbol: 'Ba',
    name: 'Barium',
    mass: 137.3,
    Z: 56,
    valences: [2],
    group: 'Alkaline earth metals',
    x: 2,
    y: 6
  },
  {
    period: 6,
    positionGroup: 3,
    inactive: false,
    symbol: 'La',
    name: 'Lanthanum',
    mass: 138.9,
    Z: 57,
    valences: [3],
    group: 'Lanthanides',
    x: 4,
    y: 9
  },
  {
    period: 6,
    positionGroup: 4,
    inactive: false,
    symbol: 'Ce',
    name: 'Cerium',
    mass: 140.1,
    Z: 58,
    valences: [3, 4],
    group: 'Lanthanides',
    x: 5,
    y: 9
  },
  {
    period: 6,
    positionGroup: 5,
    inactive: false,
    symbol: 'Pr',
    name: 'Praseodymium',
    mass: 140.9,
    Z: 59,
    valences: [3, 4],
    group: 'Lanthanides',
    x: 6,
    y: 9
  },
  {
    period: 6,
    positionGroup: 6,
    inactive: false,
    symbol: 'Nd',
    name: 'Neodymium',
    mass: 144.2,
    Z: 60,
    valences: [3],
    group: 'Lanthanides',
    x: 7,
    y: 9
  },
  {
    period: 6,
    positionGroup: 7,
    inactive: false,
    symbol: 'Pm',
    name: 'Promethium',
    mass: 145,
    Z: 61,
    valences: [3],
    group: 'Lanthanides',
    x: 8,
    y: 9
  },
  {
    period: 6,
    positionGroup: 8,
    inactive: false,
    symbol: 'Sm',
    name: 'Samarium',
    mass: 150.4,
    Z: 62,
    valences: [2, 3],
    group: 'Lanthanides',
    x: 9,
    y: 9
  },
  {
    period: 6,
    positionGroup: 9,
    inactive: false,
    symbol: 'Eu',
    name: 'Europium',
    mass: 152,
    Z: 63,
    valences: [2, 3],
    group: 'Lanthanides',
    x: 10,
    y: 9
  },
  {
    period: 6,
    positionGroup: 10,
    inactive: false,
    symbol: 'Gd',
    name: 'Gadolinium',
    mass: 157.3,
    Z: 64,
    valences: [3],
    group: 'Lanthanides',
    x: 11,
    y: 9
  },
  {
    period: 6,
    positionGroup: 11,
    inactive: false,
    symbol: 'Tb',
    name: 'Terbium',
    mass: 158.9,
    Z: 65,
    valences: [3, 4],
    group: 'Lanthanides',
    x: 12,
    y: 9
  },
  {
    period: 6,
    positionGroup: 12,
    inactive: false,
    symbol: 'Dy',
    name: 'Dysprosium',
    mass: 162.5,
    Z: 66,
    valences: [3],
    group: 'Lanthanides',
    x: 13,
    y: 9
  },
  {
    period: 6,
    positionGroup: 13,
    inactive: false,
    symbol: 'Ho',
    name: 'Holmium',
    mass: 164.9,
    Z: 67,
    valences: [3],
    group: 'Lanthanides',
    x: 14,
    y: 9
  },
  {
    period: 6,
    positionGroup: 14,
    inactive: false,
    symbol: 'Er',
    name: 'Erbium',
    mass: 167.3,
    Z: 68,
    valences: [3],
    group: 'Lanthanides',
    x: 15,
    y: 9
  },
  {
    period: 6,
    positionGroup: 15,
    inactive: false,
    symbol: 'Tm',
    name: 'Thulium',
    mass: 168.9,
    Z: 69,
    valences: [2, 3],
    group: 'Lanthanides',
    x: 16,
    y: 9
  },
  {
    period: 6,
    positionGroup: 16,
    inactive: false,
    symbol: 'Yb',
    name: 'Ytterbium',
    mass: 173,
    Z: 70,
    valences: [2, 3],
    group: 'Lanthanides',
    x: 17,
    y: 9
  },
  {
    period: 6,
    positionGroup: 17,
    inactive: false,
    symbol: 'Lu',
    name: 'Lutetium',
    mass: 175,
    Z: 71,
    valences: [3],
    group: 'Lanthanides',
    x: 18,
    y: 9
  },
  {
    period: 6,
    positionGroup: 18,
    inactive: false,
    symbol: 'Hf',
    name: 'Hafnium',
    mass: 178.5,
    Z: 72,
    valences: [4],
    group: 'Transition metals',
    x: 4,
    y: 6
  },
  {
    period: 6,
    positionGroup: 1,
    inactive: false,
    symbol: 'Ta',
    name: 'Tantalum',
    mass: 180.9,
    Z: 73,
    valences: [5],
    group: 'Transition metals',
    x: 5,
    y: 6
  },
  {
    period: 6,
    positionGroup: 2,
    inactive: false,
    symbol: 'W',
    name: 'Tungsten',
    mass: 183.8,
    Z: 74,
    valences: [2, 4, 6],
    group: 'Transition metals',
    x: 6,
    y: 6
  },
  {
    period: 6,
    positionGroup: 3,
    inactive: false,
    symbol: 'Re',
    name: 'Rhenium',
    mass: 186.2,
    Z: 75,
    valences: [4, 6],
    group: 'Transition metals',
    x: 7,
    y: 6
  },
  {
    period: 6,
    positionGroup: 4,
    inactive: false,
    symbol: 'Os',
    name: 'Osmium',
    mass: 190.2,
    Z: 76,
    valences: [4, 6, 8],
    group: 'Transition metals',
    x: 8,
    y: 6
  },
  {
    period: 6,
    positionGroup: 5,
    inactive: false,
    symbol: 'Ir',
    name: 'Iridium',
    mass: 192.2,
    Z: 77,
    valences: [3, 4],
    group: 'Transition metals',
    x: 9,
    y: 6
  },
  {
    period: 6,
    positionGroup: 6,
    inactive: false,
    symbol: 'Pt',
    name: 'Platinum',
    mass: 195.1,
    Z: 78,
    valences: [2, 4],
    group: 'Transition metals',
    x: 10,
    y: 6
  },
  {
    period: 6,
    positionGroup: 7,
    inactive: false,
    symbol: 'Au',
    name: 'Gold',
    mass: 197,
    Z: 79,
    valences: [1, 3],
    group: 'Transition metals',
    x: 11,
    y: 6
  },
  {
    period: 6,
    positionGroup: 8,
    inactive: false,
    symbol: 'Hg',
    name: 'Mercury',
    mass: 200.6,
    Z: 80,
    valences: [1, 2],
    group: 'Transition metals',
    x: 12,
    y: 6
  },
  {
    period: 6,
    positionGroup: 9,
    inactive: false,
    symbol: 'Tl',
    name: 'Thallium',
    mass: 204.4,
    Z: 81,
    valences: [1, 3],
    group: 'Post-transition metals',
    x: 13,
    y: 6
  },
  {
    period: 6,
    positionGroup: 10,
    inactive: false,
    symbol: 'Pb',
    name: 'Lead',
    mass: 207.2,
    Z: 82,
    valences: [2, 4],
    group: 'Post-transition metals',
    x: 14,
    y: 6
  },
  {
    period: 6,
    positionGroup: 11,
    inactive: false,
    symbol: 'Bi',
    name: 'Bismuth',
    mass: 208.9,
    Z: 83,
    valences: [3, 5],
    group: 'Post-transition metals',
    x: 15,
    y: 6
  },
  {
    period: 6,
    positionGroup: 12,
    inactive: false,
    symbol: 'Po',
    name: 'Polonium',
    mass: 209,
    Z: 84,
    valences: [2, 4, 6],
    group: 'Post-transition metals',
    x: 16,
    y: 6
  },
  {
    period: 6,
    positionGroup: 13,
    inactive: false,
    symbol: 'At',
    name: 'Astatine',
    mass: 210,
    Z: 85,
    valences: [-1, 1, 3, 5, 7],
    group: 'Metalloids',
    x: 17,
    y: 6
  },
  {
    period: 6,
    positionGroup: 14,
    inactive: false,
    symbol: 'Rn',
    name: 'Radon',
    mass: 222,
    Z: 86,
    valences: [0, 2],
    group: 'Noble gases',
    x: 18,
    y: 6
  },
  {
    period: 7,
    positionGroup: 1,
    inactive: false,
    symbol: 'Fr',
    name: 'Francium',
    mass: 223,
    Z: 87,
    valences: [1],
    group: 'Alkali metals',
    x: 1,
    y: 7
  },
  {
    period: 7,
    positionGroup: 2,
    inactive: false,
    symbol: 'Ra',
    name: 'Radium',
    mass: 226,
    Z: 88,
    valences: [2],
    group: 'Alkaline earth metals',
    x: 2,
    y: 7
  },
  {
    period: 7,
    positionGroup: 4,
    inactive: false,
    symbol: 'Ac',
    name: 'Actinium',
    mass: 227,
    Z: 89,
    valences: [3],
    group: 'Actinides',
    x: 4,
    y: 10
  },
  {
    period: 7,
    positionGroup: 5,
    inactive: false,
    symbol: 'Th',
    name: 'Thorium',
    mass: 232,
    Z: 90,
    valences: [4],
    group: 'Actinides',
    x: 5,
    y: 10
  },
  {
    period: 7,
    positionGroup: 6,
    inactive: false,
    symbol: 'Pa',
    name: 'Protactinium',
    mass: 231,
    Z: 91,
    valences: [5],
    group: 'Actinides',
    x: 6,
    y: 10
  },
  {
    period: 7,
    positionGroup: 7,
    inactive: false,
    symbol: 'U',
    name: 'Uranium',
    mass: 238,
    Z: 92,
    valences: [3, 4, 5, 6],
    group: 'Actinides',
    x: 7,
    y: 10
  },
  {
    period: 7,
    positionGroup: 8,
    inactive: false,
    symbol: 'Np',
    name: 'Neptunium',
    mass: 237,
    Z: 93,
    valences: [3, 4, 5, 6, 7],
    group: 'Actinides',
    x: 8,
    y: 10
  },
  {
    period: 7,
    positionGroup: 9,
    inactive: false,
    symbol: 'Pu',
    name: 'Plutonium',
    mass: 244,
    Z: 94,
    valences: [3, 4, 5, 6, 7],
    group: 'Actinides',
    x: 9,
    y: 10
  },
  {
    period: 7,
    positionGroup: 10,
    inactive: false,
    symbol: 'Am',
    name: 'Americium',
    mass: 243,
    Z: 95,
    valences: [2, 3, 4, 5, 6],
    group: 'Actinides',
    x: 10,
    y: 10
  },
  {
    period: 7,
    positionGroup: 11,
    inactive: false,
    symbol: 'Cm',
    name: 'Curium',
    mass: 247,
    Z: 96,
    valences: [3, 4],
    group: 'Actinides',
    x: 11,
    y: 10
  },
  {
    period: 7,
    positionGroup: 12,
    inactive: false,
    symbol: 'Bk',
    name: 'Berkelium',
    mass: 247,
    Z: 97,
    valences: [3, 4],
    group: 'Actinides',
    x: 12,
    y: 10
  },
  {
    period: 7,
    positionGroup: 13,
    inactive: false,
    symbol: 'Cf',
    name: 'Californium',
    mass: 251,
    Z: 98,
    valences: [2, 3, 4],
    group: 'Actinides',
    x: 13,
    y: 10
  },
  {
    period: 7,
    positionGroup: 14,
    inactive: false,
    symbol: 'Es',
    name: 'Einsteinium',
    mass: 252,
    Z: 99,
    valences: [3],
    group: 'Actinides',
    x: 14,
    y: 10
  },
  {
    period: 7,
    positionGroup: 15,
    inactive: false,
    symbol: 'Fm',
    name: 'Fermium',
    mass: 257,
    Z: 100,
    valences: [2, 3],
    group: 'Actinides',
    x: 15,
    y: 10
  },
  {
    period: 7,
    positionGroup: 16,
    inactive: false,
    symbol: 'Md',
    name: 'Mendelevium',
    mass: 258,
    Z: 101,
    valences: [2, 3],
    group: 'Actinides',
    x: 16,
    y: 10
  },
  {
    period: 7,
    positionGroup: 17,
    inactive: false,
    symbol: 'No',
    name: 'Nobelium',
    mass: 259,
    Z: 102,
    valences: [2, 3],
    group: 'Actinides',
    x: 17,
    y: 10
  },
  {
    period: 7,
    positionGroup: 18,
    inactive: false,
    symbol: 'Lr',
    name: 'Lawrencium',
    mass: 262,
    Z: 103,
    valences: [3],
    group: 'Transition metals',
    x: 18,
    y: 10
  },
  {
    period: 7,
    positionGroup: 3,
    inactive: false,
    symbol: 'Rf',
    name: 'Rutherfordium',
    mass: 267,
    Z: 104,
    valences: [],
    group: 'Transition metals',
    x: 4,
    y: 7
  },
  {
    period: 7,
    positionGroup: 4,
    inactive: false,
    symbol: 'Db',
    name: 'Dubnium',
    mass: 270,
    Z: 105,
    valences: [],
    group: 'Transition metals',
    x: 5,
    y: 7
  },
  {
    period: 7,
    positionGroup: 5,
    inactive: true,
    symbol: 'Sg',
    name: 'Seaborgium',
    mass: 271,
    Z: 106,
    valences: [],
    group: 'Transition metals',
    x: 6,
    y: 7
  },
  {
    period: 7,
    positionGroup: 6,
    inactive: true,
    symbol: 'Bh',
    name: 'Bohrium',
    mass: 270,
    Z: 107,
    valences: [],
    group: 'Transition metals',
    x: 7,
    y: 7
  },
  {
    period: 7,
    positionGroup: 7,
    inactive: true,
    symbol: 'Hs',
    name: 'Hassium',
    mass: 277,
    Z: 108,
    valences: [],
    group: 'Transition metals',
    x: 8,
    y: 7
  },
  {
    period: 7,
    positionGroup: 8,
    inactive: true,
    symbol: 'Mt',
    name: 'Meitnerium',
    mass: 276,
    Z: 109,
    valences: [],
    group: 'Unknown',
    x: 9,
    y: 7
  },
  {
    period: 7,
    positionGroup: 9,
    inactive: true,
    symbol: 'Ds',
    name: 'Darmstadtium',
    mass: 281,
    Z: 110,
    valences: [],
    group: 'Unknown',
    x: 10,
    y: 7
  },
  {
    period: 7,
    positionGroup: 10,
    inactive: true,
    symbol: 'Rg',
    name: 'Roentgenium',
    mass: 280,
    Z: 111,
    valences: [],
    group: 'Unknown',
    x: 11,
    y: 7
  },
  {
    period: 7,
    positionGroup: 11,
    inactive: true,
    symbol: 'Cn',
    name: 'Copernicium',
    mass: 285,
    Z: 112,
    valences: [],
    group: 'Transition metals',
    x: 12,
    y: 7
  },
  {
    period: 7,
    positionGroup: 12,
    inactive: true,
    symbol: 'Nh',
    name: 'Nihonium',
    mass: 284,
    Z: 113,
    valences: [],
    group: 'Unknown',
    x: 13,
    y: 7
  },
  {
    period: 7,
    positionGroup: 13,
    inactive: true,
    symbol: 'Fl',
    name: 'Flerovium',
    mass: 289,
    Z: 114,
    valences: [],
    group: 'Post-transition metals',
    x: 14,
    y: 7
  },
  {
    period: 7,
    positionGroup: 14,
    inactive: true,
    symbol: 'Mc',
    name: 'Moscovium',
    mass: 288,
    Z: 115,
    valences: [],
    group: 'Unknown',
    x: 15,
    y: 7
  },
  {
    period: 7,
    positionGroup: 15,
    inactive: true,
    symbol: 'Lv',
    name: 'Livermorium',
    mass: 293,
    Z: 116,
    valences: [],
    group: 'Unknown',
    x: 16,
    y: 7
  },
  {
    period: 7,
    positionGroup: 16,
    inactive: true,
    symbol: 'Ts',
    name: 'Tennessine',
    mass: 294,
    Z: 117,
    valences: [],
    group: 'Unknown',
    x: 17,
    y: 7
  },
  {
    period: 7,
    positionGroup: 17,
    inactive: true,
    symbol: 'Og',
    name: 'Oganesson',
    mass: 294,
    Z: 118,
    valences: [],
    group: 'Unknown',
    x: 18,
    y: 7
  }
];

export const themes: Record<string, any> = {
  'Alkali metals': '#ecbe59',
  'Alkaline earth metals': '#dee955',
  Lanthanides: '#ec77a3',
  Actinides: '#c686cc',
  'Transition metals': '#fd8572',
  'Post-transition metals': '#4cddf3',
  'Other nonmetals': '#52ee61',
  'Noble gases': '#759fff',
  Metalloids: '#3aefb6'
};

export const atom_radius = [
  { Z: 1, radius: 120 },
  { Z: 2, radius: 140 },
  { Z: 3, radius: 182 },
  { Z: 4, radius: 153 },
  { Z: 5, radius: 192 },
  { Z: 6, radius: 170 },
  { Z: 7, radius: 155 },
  { Z: 8, radius: 152 },
  { Z: 9, radius: 135 },
  { Z: 10, radius: 154 },
  { Z: 11, radius: 227 },
  { Z: 12, radius: 173 },
  { Z: 13, radius: 184 },
  { Z: 14, radius: 210 },
  { Z: 15, radius: 180 },
  { Z: 16, radius: 180 },
  { Z: 17, radius: 175 },
  { Z: 18, radius: 188 },
  { Z: 19, radius: 275 },
  { Z: 20, radius: 231 },
  { Z: 21, radius: 211 },
  { Z: 22, radius: 187 },
  { Z: 23, radius: 179 },
  { Z: 24, radius: 189 },
  { Z: 25, radius: 197 },
  { Z: 26, radius: 194 },
  { Z: 27, radius: 192 },
  { Z: 28, radius: 163 },
  { Z: 29, radius: 140 },
  { Z: 30, radius: 139 },
  { Z: 31, radius: 187 },
  { Z: 32, radius: 211 },
  { Z: 33, radius: 185 },
  { Z: 34, radius: 190 },
  { Z: 35, radius: 183 },
  { Z: 36, radius: 202 },
  { Z: 37, radius: 303 },
  { Z: 38, radius: 249 },
  { Z: 39, radius: 219 },
  { Z: 40, radius: 186 },
  { Z: 41, radius: 207 },
  { Z: 42, radius: 209 },
  { Z: 43, radius: 209 },
  { Z: 44, radius: 207 },
  { Z: 45, radius: 195 },
  { Z: 46, radius: 202 },
  { Z: 47, radius: 172 },
  { Z: 48, radius: 158 },
  { Z: 49, radius: 193 },
  { Z: 50, radius: 217 },
  { Z: 51, radius: 206 },
  { Z: 52, radius: 206 },
  { Z: 53, radius: 198 },
  { Z: 54, radius: 216 },
  { Z: 55, radius: 343 },
  { Z: 56, radius: 268 },
  { Z: 57, radius: 240 },
  { Z: 58, radius: 235 },
  { Z: 59, radius: 239 },
  { Z: 60, radius: 229 },
  { Z: 61, radius: 236 },
  { Z: 62, radius: 229 },
  { Z: 63, radius: 233 },
  { Z: 64, radius: 237 },
  { Z: 65, radius: 221 },
  { Z: 66, radius: 229 },
  { Z: 67, radius: 216 },
  { Z: 68, radius: 235 },
  { Z: 69, radius: 227 },
  { Z: 70, radius: 242 },
  { Z: 71, radius: 221 },
  { Z: 72, radius: 212 },
  { Z: 73, radius: 217 },
  { Z: 74, radius: 210 },
  { Z: 75, radius: 217 },
  { Z: 76, radius: 216 },
  { Z: 77, radius: 202 },
  { Z: 78, radius: 209 },
  { Z: 79, radius: 166 },
  { Z: 80, radius: 209 },
  { Z: 81, radius: 196 },
  { Z: 82, radius: 202 },
  { Z: 83, radius: 207 },
  { Z: 84, radius: 197 },
  { Z: 85, radius: 202 },
  { Z: 86, radius: 220 },
  { Z: 87, radius: 348 },
  { Z: 88, radius: 283 },
  { Z: 89, radius: 260 },
  { Z: 90, radius: 237 },
  { Z: 91, radius: 243 },
  { Z: 92, radius: 240 },
  { Z: 93, radius: 221 },
  { Z: 94, radius: 243 },
  { Z: 95, radius: 244 },
  { Z: 96, radius: 245 },
  { Z: 97, radius: 244 },
  { Z: 98, radius: 245 },
  { Z: 99, radius: 245 },
  { Z: 100, radius: 245 }
];
